### PR TITLE
86 initial feedback small fast fixes

### LINKED ISSUE #86: Initial feedback from Kristina
Hi everyone, just had a peek at the Heroku and it's looking awesome! Great work over there - I have heard that things are a bit crazy so a big thank you for continuing to work at home.

I will be going through the app with Katia tonight around 5pm London time so I'll be able to send some initial feedback then.

Looking through it, here are a few things that I have already noticed:

1. Add recommendation button is not properly aligned (in mobile or desktop)
Screen Shot 2019-11-14 at 09 14 46

2. If possible, Katia would prefer that countries/cities that do not yet have a Sitspot are not shown on the dropdown in the search. Preferably, it would look something like this, with the numbers representing the number of sitspots in that place:
https://www.holiable.com/lodging/hotel/
Screen Shot 2019-11-14 at 09 26 19

3. Would be great if the nav menu automatically closes after a link is clicked on, as opposed to staying open
Screen Shot 2019-11-14 at 09 31 05

4. Copy for FAQs still need to be updated (plus there are some typos on the headings that have been added to heroku, so please have a look when you are adding the new stuff in)
https://onedrive.live.com/view.aspx?cid=b2508299104e0036&page=view&resid=B2508299104E0036!8649&parId=B2508299104E0036!8738&authkey=!AOxjVt8ILmwns8s&app=Word

5. The link for adding a new Sitspot reads a bit too casual and has a capitalisation error. I would suggest 'Would you like to add a new SitSpot?
Screen Shot 2019-11-14 at 09 34 37

6. KeyWords in the filter search should be spelled 'Keywords'
Screen Shot 2019-11-14 at 09 37 07

7. Ideally the keywords menu will eventually have icons beside the words
https://user-images.githubusercontent.com/56404750/68476342-54055280-0222-11ea-8d34-257d6857206e.png

8. At the moment, I haven't been able to search any existing sitspots as I don't think they are linked. Katia did mention that  she has made 3 of each business type

9. When trying to add a Sitspot, I get a 500 when trying to add a photo and cannot move one
Screen Shot 2019-11-14 at 09 41 55

10. I haven't seen the user info form - does that come next?

Overall, SUPER work. I am extremely impressed by everything so far. Ideally it would be best if the add a sitspot functionality was working by tonight, and that there is at least one Sitspot page rendered so that Katia can have an idea of what it looks like. Thanks team!!!!! You are awesome!

### PR DESCRIPTION
**Pull request by Amoodaa**
#86 #90

### CODE REVIEW

File: server/controllers/utils/formatReviews.js [hunk 1]
```diff
@@ -64,9 +58,11 @@ const format = review => {
 
   // magical factors
   copy.magicalFactors = keys
-    .filter(e => e.split('_')[0] === 'mf')
+    .filter(e => {
+      const key = e.split('_')[0];
+      return key === 'mf' || key === 'bc';
```
Comment (11janci) [inline server/controllers/utils/formatReviews.js]: do not hardcode string literals that are used for logic, use enums/constants

File: client/src/pages/Search/index.js [hunk 2]
```diff
@@ -11,6 +11,18 @@ class SearchPage extends Component {
...
 
+  componentDidMount() {
+    const { searchState } = this.props;
+    if (
+      searchState &&
+      !(
+        Object.entries(searchState).length === 0 &&
+        searchState.constructor === Object
+      )
+    )
```
Comment (11janci) [inline client/src/pages/Search/index.js]: hm, the way the `searchState` is done doesn't seem right. It should simply be created, kept and used within the `Search` component, shouldn't be here at all, what is the reason for that? Plus, this is a top level page, so it will always be set to `{}`?

Of course I don't expect you to refactor it at this point, just wanted to point out.

Comment (Amoodaa) [reply client/src/pages/Search/index.js]: Yes the reason is, we want to keep the state of the search between the Home page, and the search page, and I wanted to make the API request only in the search page, so if it has a state on componentDidMount then do the API request

File: server/controllers/utils/formatReviews.js (hunk 1 above)
Comment (Amoodaa) [reply server/controllers/utils/formatReviews.js]: these are coming from Airtable, that's a quick trick, its actually more flexible than u think XD
you can see the fields in the stay, eat, shop: https://airtable.com/shrWi4h598CkxhYlV

Comment (Amoodaa) [reply server/controllers/utils/formatReviews.js]: will delete link soon

Comment (11janci) [reply server/controllers/utils/formatReviews.js]: my point was that you should put `'mf'` and `'bc'` into an enum/constant and not hardcode it. Also, to improve readability, it would be good to put it into a function `isMagicalFactor()`, so it would look like `.filter(e => isMagicalFactor(e))`

As for the solution, it would be worth considering having just one field in the database containing all of the magical factors in a string/array (e.g. `local_immersion staff_interaction`), instead of having a separate field for each magical factor. It would be more flexible - adding or removing new magical factors wouldn't require changing the DB schema and here you wouldn't have to do these shenanigans with the object's keys.

Comment (Amoodaa) [reply server/controllers/utils/formatReviews.js]: there is a field named: `magical factors` but its not 'keyed', and id be using string and maybe emojis to compare strings, but the thing is in the typeform, when the user picks a magical factor, he is asked to fill another single line text field, which are the ones prefixed with `mf` or `bc`

File: client/src/pages/Search/index.js (hunk 2 above)
Comment (11janci) [reply client/src/pages/Search/index.js]: ok I think I understand. So essentially you wanna have sort of a "global" state for the component. Redux would be great here, implementing it for yourself is doable but not trivial.. But ok you found a working solution so.. :)

File: server/controllers/utils/formatReviews.js (hunk 1 above)
Comment (11janci) [reply server/controllers/utils/formatReviews.js]: ok I'm obviously missing information about the whole thing so can't really comment on that 🙂

Comment (11janci) [reply server/controllers/utils/formatReviews.js]: but that comment about not hardcoding strings stands 😉
